# Generated by Django 4.2 on 2023-06-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0008_alter_alamatpengiriman_options_payment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='harga',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='harga_diskon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
