# Generated by Django 4.2 on 2023-06-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0009_produkitem_rating_alter_produkitem_kategori_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='produk_items',
            new_name='produk',
        ),
    ]
