# Generated by Django 4.2 on 2023-06-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0010_rename_produk_items_rating_produk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkitem',
            name='rating',
        ),
    ]
